### ISSUE TITLE
Remove Exposed API Keys

### ISSUE THREAD

**Issue by hopeman15** [Danau5tin/Easy-Split-Android-App#1]
The `google-services.json` exposes private API keys. You should remove these asap as it leaves your app and its services open to hackers.

**TODO:**
- [ ] Remove `google-services.json` from public repository (.gitignore)
- [ ] Create new API keys in Firebase
- [ ] Invalidate exposed keys

**Comment by Danau5tin** [comment]
Have done this, thank you for your assistance.
